local T = _G.TeamBestLootPriority
T.loot = {
	['3365']={name='Imperial Qiraji Armaments',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21222']={name='Imperial Qiraji Armaments',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21227']={name='Imperial Qiraji Regalia',prio='Ferals -> everyone else',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21648']={name='Recomposed Boots',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21666']={name='Sarturas Might',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21667']={name='Legplates Of Blazing Light',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21668']={name='Scaled Leggings of Qiraji Fury',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21669']={name='Creeping Vine Helm',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21670']={name='Badge of the Swarmguard',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21671']={name='Robes Of the Battleguard',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21672']={name='Gloves of Enforcement',prio='Ferals -> everyone else',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21673']={name='Silithid Claw',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21674']={name='Gauntlets of Steadfast Determination',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21675']={name='Thick Qirajihide Belt',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21676']={name='Leggiungs of the Festering Swarm',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21678']={name='Necklace of Purity',prio='No Prio',zone='AhnQiraj',boss='Battleguard Sartura'},
	['21222']={name='Imperial Qiraji Armaments',prio='No Prio',zone='AhnQiraj',boss='BugTrio'},
	['21227']={name='Imperial Qiraji Regalia',prio='Ferals -> everyone else',zone='AhnQiraj',boss='BugTrio'},
	['21603']={name='Wand of Qiraji Nobility',prio='Kri last',zone='AhnQiraj',boss='BugTrio'},
	['21680']={name='Vest of Swift Execution',prio=' Cat DPS -> tank',zone='AhnQiraj',boss='BugTrio'},
	['21681']={name='Ring of the Devoured',prio='Kri last',zone='AhnQiraj',boss='BugTrio'},
	['21682']={name='Bile-Covered Gauntlets',prio='Yauj last',zone='AhnQiraj',boss='BugTrio'},
	['21683']={name='Mantle of the Desert Crusade',prio='Yauj last',zone='AhnQiraj',boss='BugTrio'},
	['21684']={name='Mantle of the Desserts Fury',prio='Yauj last',zone='AhnQiraj',boss='BugTrio'},
	['21685']={name='Petrified Scarab',prio='Kri last',zone='AhnQiraj',boss='BugTrio'},
	['21686']={name='Mattle OF Phrenic Power',prio='Yauj last',zone='AhnQiraj',boss='BugTrio'},
	['21687']={name='Ukkos ring of Darkness',prio='Warlock (Tanks Emps)',zone='AhnQiraj',boss='BugTrio'},
	['21688']={name='Boots of the Fallen Hero',prio='Vem last',zone='AhnQiraj',boss='BugTrio'},
	['21689']={name='Gloves of Ebru',prio='Vem last',zone='AhnQiraj',boss='BugTrio'},
	['21690']={name='Angelistas Charm',prio='Vem last',zone='AhnQiraj',boss='BugTrio'},
	['21691']={name='Ooze-ridden Gauntlets',prio='Vem last',zone='AhnQiraj',boss='BugTrio'},
	['21692']={name='Triad Girdle',prio='No Prio',zone='AhnQiraj',boss='BugTrio'},
	['21693']={name='Guise OF the Devourer',prio='No Prio',zone='AhnQiraj',boss='BugTrio'},
	['21694']={name='Ternary Mantle',prio='Priest -> everyone else',zone='AhnQiraj',boss='BugTrio'},
	['21695']={name='Angelistas Touch',prio='No Prio',zone='AhnQiraj',boss='BugTrio'},
	['21696']={name='Robes of the Triumvirate',prio='No Prio',zone='AhnQiraj',boss='BugTrio'},
	['21697']={name='Cape of the Trinity',prio='No Prio',zone='AhnQiraj',boss='BugTrio'},
	['20929']={name='Carapace of the Old God',prio='Warrior Tank -> everyone else',zone='AhnQiraj',boss='Cthun'},
	['20933']={name='Husk of the Old God',prio='Mage/Shadow Priest -> Warlock -> everyone else',zone='AhnQiraj',boss='Cthun'},
	['21126']={name='Deaths Sting',prio='Dagger Rogue -> Sword Rogue/Warrior Tank -> everyone else',zone='AhnQiraj',boss='Cthun'},
	['21134']={name='Dark Edge of Insanity',prio='No Prio',zone='AhnQiraj',boss='Cthun'},
	['21221']={name='Eye of Cthun',prio='Caster/Healers -> everyone else',zone='AhnQiraj',boss='Cthun'},
	['21579']={name='Vanquished tentacle of Cthun',prio='No Prio',zone='AhnQiraj',boss='Cthun'},
	['21581']={name='Gauntlets of Annihilation',prio='No Prio',zone='AhnQiraj',boss='Cthun'},
	['21582']={name='Grasp of the Old God',prio='Priest -> everyone else',zone='AhnQiraj',boss='Cthun'},
	['21583']={name='Cloak of clarity',prio='No Prio',zone='AhnQiraj',boss='Cthun'},
	['21585']={name='Dark Storm Gauntlets',prio='No Prio',zone='AhnQiraj',boss='Cthun'},
	['21586']={name='Belt of Never-Ending Agony',prio='Rogue/Druid DPS -> everyone else',zone='AhnQiraj',boss='Cthun'},
	['21596']={name='Ring of the Godslayer',prio='No Prio',zone='AhnQiraj',boss='Cthun'},
	['21839']={name='Scepter of the False Prophet',prio='No Prio',zone='AhnQiraj',boss='Cthun'},
	['22730']={name='Eyestalk Waist Cord',prio='Mage/Warlock -> Shadow Priest -> everyone else',zone='AhnQiraj',boss='Cthun'},
	['22731']={name='Cloak of the Devoured',prio='No Prio',zone='AhnQiraj',boss='Cthun'},
	['22732']={name='Mark of Cthun',prio='No Prio',zone='AhnQiraj',boss='Cthun'},
	['21222']={name='Imperial Qiraji Armaments',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21227']={name='Imperial Qiraji Regalia',prio='Ferals -> everyone else',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21627']={name='Cloak of Untold Secrets',prio='Warlock Tanks',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21635']={name='Barb of The Sand Reaver',prio='Meleeweaving -> everyone else',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21639']={name='Pauldrons of the Unrelenting',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21645']={name='Hive Tunnelers Boots',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21647']={name='Fetish of the Sand Reaver',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21650']={name='Ancient Qiraji Ripper',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21651']={name='Scaled Sand Reaver Leggings',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21652']={name='Silithid Carapace Chestguard',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21663']={name='Robes of the guardian Saint',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21664']={name='Barbed choker',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['21665']={name='Mantle of Wicked Revenge',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['22396']={name='Totem of life',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['22402']={name='Libram of Grace',prio='No Prio',zone='AhnQiraj',boss='Fankriss The Unyielding'},
	['20927']={name='Ouros Intact Hide',prio='Warrior Tank -> Dps Warrior / Rogue / Shadowpriest -> Mage -> Priest Healer',zone='AhnQiraj',boss='Ouro'},
	['20931']={name='Skin of the Great Sandworm',prio='No Prio',zone='AhnQiraj',boss='Ouro'},
	['21222']={name='Imperial Qiraji Armaments',prio='No Prio',zone='AhnQiraj',boss='Ouro'},
	['21227']={name='Imperial Qiraji Regalia',prio='Ferals -> everyone else',zone='AhnQiraj',boss='Ouro'},
	['21610']={name='Wormscale Blocker',prio='No Prio',zone='AhnQiraj',boss='Ouro'},
	['21611']={name='Burrower Bracers',prio='Shadow Priest -> everyone else',zone='AhnQiraj',boss='Ouro'},
	['21615']={name='Don Rigobertos Lost Hat',prio='No Prio',zone='AhnQiraj',boss='Ouro'},
	['23557']={name='Larvea of the Great Worm',prio='No Prio',zone='AhnQiraj',boss='Ouro'},
	['23558']={name='The Burrowers Shell',prio='No Prio',zone='AhnQiraj',boss='Ouro'},
	['23570']={name='Jom Gabbar',prio='Hunter -> Melee',zone='AhnQiraj',boss='Ouro'},
	['20928']={name='Qiraji Bindings of Command',prio='Warrior/Rogues -> Everyone else (for shoulders only)',zone='AhnQiraj',boss='Princess Huhuran'},
	['20932']={name='Qirtaji Bindings of Dominance',prio='Mage/Warlock/Paladin DPS -> everyone else',zone='AhnQiraj',boss='Princess Huhuran'},
	['21222']={name='Imperial Qiraji Armaments',prio='No Prio',zone='AhnQiraj',boss='Princess Huhuran'},
	['21227']={name='Imperial Qiraji Regalia',prio='No Prio',zone='AhnQiraj',boss='Princess Huhuran'},
	['21616']={name='Huhurans stinger',prio='No Prio',zone='AhnQiraj',boss='Princess Huhuran'},
	['21617']={name='Wasphide Gauntlets',prio='Druid -> Paladin',zone='AhnQiraj',boss='Princess Huhuran'},
	['21618']={name='Hive Defiler Wristguards',prio='No Prio',zone='AhnQiraj',boss='Princess Huhuran'},
	['21619']={name='Gloves of the Messiah',prio='No Prio',zone='AhnQiraj',boss='Princess Huhuran'},
	['21620']={name='Ring of the Martyr',prio='No Prio',zone='AhnQiraj',boss='Princess Huhuran'},
	['21621']={name='Cloak of the Golden Hive',prio='No Prio',zone='AhnQiraj',boss='Princess Huhuran'},
	['21128']={name='Staff of the Qiraji Prophet',prio='Warlock tanks',zone='AhnQiraj',boss='Prophet Skeram'},
	['21232']={name='Imperial Qiraji Armaments',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21237']={name='Imperial Qiraji Regalia',prio='Ferals -> everyone else',zone='AhnQiraj',boss='Prophet Skeram'},
	['21698']={name='Leggings of Immersion',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21699']={name='Barrage Shoulders',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21700']={name='Pendant of the Qiraji Guardian',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21701']={name='Cloak of Concentrated Hatred',prio='Tanks -> Melee',zone='AhnQiraj',boss='Prophet Skeram'},
	['21702']={name='Amulet of Foul Warding',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21703']={name='Hammer OF Jizhi',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21704']={name='Boots of the Redeemed Prophecy',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21705']={name='Boots Of the Fallen Prophet',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21706']={name='Boots of the Unwavering Will',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21707']={name='Ring Of Swarming Thought',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21708']={name='Beetle Scaled Wristguards',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21814']={name='Breastplate of Annihilation',prio='No Prio',zone='AhnQiraj',boss='Prophet Skeram'},
	['21836']={name='Ritssyns Ring of Chaos',prio='Mage -> everyone else',zone='AhnQiraj',boss='Thrash'},
	['21837']={name='Anubisath Warhammer',prio='Whoever wants it',zone='AhnQiraj',boss='Thrash'},
	['21838']={name='Garb of Royal Ascension',prio='Warlock (Tanks Emps)',zone='AhnQiraj',boss='Thrash'},
	['21888']={name='Gloves of the Immortal',prio='Whoever wants it',zone='AhnQiraj',boss='Thrash'},
	['21889']={name='Gloves of the Redeemed Prophecy',prio='Whoever wants it',zone='AhnQiraj',boss='Thrash'},
	['21891']={name='Shard of the Fallen Star',prio='Whoever wants it',zone='AhnQiraj',boss='Thrash'},
	['21856']={name='Neretzek  The Blood Drinker',prio='Whoever wants it',zone='AhnQiraj',boss='Trash'},
	['20926']={name='Veknilashs circlet',prio='warr tanks -> locks/SP -> mages -> dps warrs/healers',zone='AhnQiraj',boss='Twin Emperors'},
	['20930']={name='Veklors Diadem',prio='Rogue/Paladin -> everyone else',zone='AhnQiraj',boss='Twin Emperors'},
	['21222']={name='Imperial Qiraji Armaments',prio='No Prio',zone='AhnQiraj',boss='Twin Emperors'},
	['21227']={name='Imperial Qiraji Regalia',prio='Ferals -> everyone else',zone='AhnQiraj',boss='Twin Emperors'},
	['21597']={name='Royal Scepter of Veklor',prio='Mage/Warlock -> Shadow Priest',zone='AhnQiraj',boss='Twin Emperors'},
	['21598']={name='Royal Qiraji Belt',prio='No Prio',zone='AhnQiraj',boss='Twin Emperors'},
	['21599']={name='Veklors Gloves of Devastation',prio='No Prio',zone='AhnQiraj',boss='Twin Emperors'},
	['21600']={name='Boots of Epiphany',prio='Shadow Priest -> everyone else',zone='AhnQiraj',boss='Twin Emperors'},
	['21601']={name='Ring of Emporer Veklor',prio='Druid -> everyone else',zone='AhnQiraj',boss='Twin Emperors'},
	['21602']={name='Qiraji Execution Bracers',prio='Druid -> Warrior -> everyone else',zone='AhnQiraj',boss='Twin Emperors'},
	['21604']={name='Bracelets of Royal Redemption',prio='No Prio',zone='AhnQiraj',boss='Twin Emperors'},
	['21605']={name='Gloves of the Hidden Temple',prio='No Prio',zone='AhnQiraj',boss='Twin Emperors'},
	['21606']={name='Belt of the Fallen Emperor',prio='No Prio',zone='AhnQiraj',boss='Twin Emperors'},
	['21607']={name='Grasp of the Fallen Emperor',prio='No Prio',zone='AhnQiraj',boss='Twin Emperors'},
	['21608']={name='Amulet of Veknilash',prio='DPS -> Healer',zone='AhnQiraj',boss='Twin Emperors'},
	['21609']={name='Regenerating Belt of Veknilash',prio='No Prio',zone='AhnQiraj',boss='Twin Emperors'},
	['21679']={name='Kalimdors Revenge',prio='No Prio',zone='AhnQiraj',boss='Twin Emperors'},
	['20928']={name='Qiraji Bindings of Command',prio='Warrior/Rogues -> everyone else (for shoulders only)',zone='AhnQiraj',boss='Viscidus'},
	['20932']={name='Qirtaji Bindings of Dominance',prio='Mage/Warlock/Paladin DPS -> everyone else',zone='AhnQiraj',boss='Viscidus'},
	['21222']={name='Imperial Qiraji Armaments',prio='No Prio',zone='AhnQiraj',boss='Viscidus'},
	['21227']={name='Imperial Qiraji Regalia',prio='Ferals -> everyone else',zone='AhnQiraj',boss='Viscidus'},
	['21622']={name='Sharpened Silithid Femur',prio='No Prio',zone='AhnQiraj',boss='Viscidus'},
	['21623']={name='Gauntlets of the Righteous Champion',prio='No Prio',zone='AhnQiraj',boss='Viscidus'},
	['21624']={name='Gauntlets of Kalimdor',prio='No Prio',zone='AhnQiraj',boss='Viscidus'},
	['21625']={name='Scarab Brooch',prio='No Prio',zone='AhnQiraj',boss='Viscidus'},
	['21626']={name='Slime-coated Leggings',prio='No Prio',zone='AhnQiraj',boss='Viscidus'},
	['21677']={name='Ring of the Qiraji Fury',prio='No Prio',zone='AhnQiraj',boss='Viscidus'},
	['22399']={name='Idol of Health',prio='No Prio',zone='AhnQiraj',boss='Viscidus'},
	['16898']={name='Stormrage Boots',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['16906']={name='Bloodfang Boots',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['16912']={name='Netherwind Boots',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['16919']={name='Boots of Transcendence',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['16927']={name='Nemesis Boots',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['16941']={name='Dragonstalker s Greaves',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['16949']={name='Greaves of Ten Storms',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['16957']={name='Judgement Sabatons',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['16965']={name='Sabatons of Wrath',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['19341']={name='Lifegiving Gem',prio='Tank Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['19342']={name='Venomous Totem',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['19350']={name='Heartstriker',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['19351']={name='Maladath Runed Blade of the Black Flight',prio='DPS -> Tanks',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['19373']={name='Black Brood Pauldrons',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['19374']={name='Bracers of Arcane Accuracy',prio='No Prio',zone='Blackwing Lair',boss='Broodlord Lasher'},
	['16832']={name='Bloodfang Spaulders',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['16902']={name='Stormrage Pauldrons',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['16917']={name='Netherwind Mantle',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['16924']={name='Pauldrons of Transcendence',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['16932']={name='Nemesis Spaulders',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['16937']={name='Dragonstalker s Spaulders',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['16945']={name='Epaulets of Ten Storms',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['16953']={name='Judgement Spaulders',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['16961']={name='Pauldrons of Wrath',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['19347']={name='Claw of Chromaggus',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['19349']={name='Elementium Reinforced Bulwark',prio='Warrior tank',zone='Blackwing Lair',boss='Chromaggus'},
	['19352']={name='Chromatically Tempered Sword',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['19361']={name='Ashjre thul Crossbow of Smiting',prio='Hunter',zone='Blackwing Lair',boss='Chromaggus'},
	['19385']={name='Empowered Leggings',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['19386']={name='Elementium Threaded Cloak',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['19387']={name='Chromatic Boots',prio='DPS -> Tanks',zone='Blackwing Lair',boss='Chromaggus'},
	['19388']={name='Angelista s Grasp',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['19389']={name='Taut Dragonhide Shoulderpads',prio='Druid Tank -> Druid DPS',zone='Blackwing Lair',boss='Chromaggus'},
	['19390']={name='Taut Dragonhide Gloves',prio='Paladin Healer',zone='Blackwing Lair',boss='Chromaggus'},
	['19391']={name='Shimmering Geta',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['19392']={name='Girdle of the Fallen Crusader',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['19393']={name='Primalist s Linked Waistguard',prio='No Prio',zone='Blackwing Lair',boss='Chromaggus'},
	['19345']={name='Aegis of Preservation',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc'},
	['19368']={name='Dragonbreath Hand Cannon',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc'},
	['19403']={name='Band of Forced Concentration',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc'},
	['19405']={name='Malfurion s Blessed Bulwark',prio='Druid -> warriors',zone='Blackwing Lair',boss='Ebonroc'},
	['19406']={name='Drake Fang Talisman',prio='Melee/Tanks -> Hunters',zone='Blackwing Lair',boss='Ebonroc'},
	['19407']={name='Ebony Flame Gloves',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc'},
	['16899']={name='Stormrage Handguards',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['16907']={name='Bloodfang Gloves',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['16907']={name='Drakefang Talisman',prio='Melee ---> Hunter',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['16913']={name='Netherwind Gloves',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['16920']={name='Handguards of Transcendence',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['16928']={name='Nemesis Gloves',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['16940']={name='Dragonstalker s Gauntlets',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['16948']={name='Gauntlets of Ten Storms',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['16956']={name='Judgement Gauntlets',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['16964']={name='Gauntlets of Wrath',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['19353']={name='Drake Talon Cleaver',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['19355']={name='Shadow Wing Focus Staff',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['19394']={name='Drake Talon Pauldrons',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['19395']={name='Rejuvenating Gem',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['19396']={name='Taut Dragonhide Belt',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['19397']={name='Ring of Blackrock',prio='No Prio',zone='Blackwing Lair',boss='Ebonroc Firemaw Flamegor'},
	['19343']={name='Scrolls of Blinding Light',prio='No Prio',zone='Blackwing Lair',boss='Firemaw'},
	['19344']={name='Natural Alignment Crystal',prio='No Prio',zone='Blackwing Lair',boss='Firemaw'},
	['19365']={name='Claw of the Black Drake',prio='No Prio',zone='Blackwing Lair',boss='Firemaw'},
	['19398']={name='Cloak of Firemaw',prio='Rogue Prio',zone='Blackwing Lair',boss='Firemaw'},
	['19399']={name='Black Ash Robe',prio='No Prio',zone='Blackwing Lair',boss='Firemaw'},
	['19400']={name='Firemaw s Clutch',prio='No Prio',zone='Blackwing Lair',boss='Firemaw'},
	['19401']={name='Primalist s Linked Legguards',prio='No Prio',zone='Blackwing Lair',boss='Firemaw'},
	['19402']={name='Legguards of the Fallen Crusader',prio='No Prio',zone='Blackwing Lair',boss='Firemaw'},
	['19357']={name='Herald of Woe',prio='No Prio',zone='Blackwing Lair',boss='Flamegor'},
	['19367']={name='Dragon s Touch',prio='No Prio',zone='Blackwing Lair',boss='Flamegor'},
	['19430']={name='Shroud of Pure Thought',prio='No Prio',zone='Blackwing Lair',boss='Flamegor'},
	['19431']={name='Styleen s Impeding Scarab',prio='Warrior Tank Prio',zone='Blackwing Lair',boss='Flamegor'},
	['19432']={name='Circle of Applied Force',prio='Druid DPS -> melee DPS / tanks',zone='Blackwing Lair',boss='Flamegor'},
	['19433']={name='Emberweave Leggings',prio='No Prio',zone='Blackwing Lair',boss='Flamegor'},
	['16897']={name='Stormrage Chestguard',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['16905']={name='Bloodfang Chestpiece',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['16916']={name='Netherwind Robes',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['16923']={name='Robes of Transcendence',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['16931']={name='Nemesis Robes',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['16942']={name='Dragonstalker s Breastplate',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['16950']={name='Breastplate of Ten Storms',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['16958']={name='Judgement Breastplate',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['16966']={name='Breastplate of Wrath',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['19003']={name='Head of Nefarian',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['19356']={name='Staff of the Shadow Flame',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['19360']={name='Lok amir il Romathis',prio='Shadowpriest -> Paladin Healer ( withouit mageblade) / Druid Healer -> priest healer / Paladin healer ( with mageblade)',zone='Blackwing Lair',boss='Nefarian'},
	['19363']={name='Crul shorukh Edge of Chaos',prio='Melee DPS -> hunters/Tanks(threat)',zone='Blackwing Lair',boss='Nefarian'},
	['19364']={name='Ashkandi Greatsword of the Brotherhood',prio='Melee 2H PVE -> Hunter (meleeweaving) -> OS/PVP',zone='Blackwing Lair',boss='Nefarian'},
	['19375']={name='Mish undare Circlet of the Mind Flayer',prio='DPS -> Healer',zone='Blackwing Lair',boss='Nefarian'},
	['19376']={name='Archimtiros Ring of Reckoning',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['19377']={name='Prestor s Talisman of Connivery',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['19378']={name='Cloak of the Brood Lord',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['19379']={name='Neltharion s Tear',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['19380']={name='Therazane s Link',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['19381']={name='Boots of the Shadow Flame',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['19382']={name='Pure Elementium Band',prio='No Prio',zone='Blackwing Lair',boss='Nefarian'},
	['19354']={name='Draconic Avenger',prio='No Prio',zone='Blackwing Lair',boss='Random Mobs'},
	['19358']={name='Draconic Maul',prio='No Prio',zone='Blackwing Lair',boss='Random Mobs'},
	['19362']={name='Doom s Edge',prio='Melee DPS -> hunters/Tanks',zone='Blackwing Lair',boss='Random Mobs'},
	['19434']={name='Band of Dark Dominion',prio='No Prio',zone='Blackwing Lair',boss='Random Mobs'},
	['19435']={name='Essence Gatherer',prio='No Prio',zone='Blackwing Lair',boss='Random Mobs'},
	['19436']={name='Cloak of Draconic Might',prio='No Prio',zone='Blackwing Lair',boss='Random Mobs'},
	['19437']={name='Boots of Pure Thought',prio='No Prio',zone='Blackwing Lair',boss='Random Mobs'},
	['19438']={name='Ringo s Blizzard Boots',prio='No Prio',zone='Blackwing Lair',boss='Random Mobs'},
	['19439']={name='Interlaced Shadow Jerkin',prio='No Prio',zone='Blackwing Lair',boss='Random Mobs'},
	['16904']={name='Stormrage Bracers',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['16911']={name='Bloodfang Bracers',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['16918']={name='Netherwind Bindings',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['16926']={name='Bindings of Transcendence',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['16934']={name='Nemesis Bracers',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['16935']={name='Dragonstalker s Bracers',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['16943']={name='Bracers of Ten Storms',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['16951']={name='Judgement Bindings',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['16959']={name='Bracelets of Wrath',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['19334']={name='The Untamed Blade',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['19335']={name='Spineshatter',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['19336']={name='Arcane Infused Gem',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['19337']={name='The Black Book',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['19369']={name='Gloves of Rapid Evolution',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['19370']={name='Mantle of the Blackwing Cabal',prio='No Prio',zone='Blackwing Lair',boss='Razorgore the Untamed'},
	['16818']={name='Netherwind Belt',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['16903']={name='Stormrage Belt',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['16910']={name='Bloodfang Belt',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['16925']={name='Belt of Transcendence',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['16933']={name='Nemesis Belt',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['16936']={name='Dragonstalker s Belt',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['16944']={name='Belt of Ten Storms',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['16952']={name='Judgement Belt',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['16960']={name='Waistband of Wrath',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['19339']={name='Mind Quickening Gem',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['19340']={name='Rune of Metamorphosis',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['19346']={name='Dragonfang Blade',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['19348']={name='Red Dragonscale Protector',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['19371']={name='Pendant of the Fallen Dragon',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['19372']={name='Helm of Endless Rage',prio='No Prio',zone='Blackwing Lair',boss='Vaelastrasz the Corrupt'},
	['17077']={name='Crimson Shocker',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['18820']={name='Talisman of Ephemeral Power',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['18861']={name='Flamewaker Legplates',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['18870']={name='Helm of the Lifegiver',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['18872']={name='Manastorm Leggings',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['18875']={name='Salamander Scale Pants',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['18878']={name='Sorcerous Dagger',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['18879']={name='Heavy Dark Iron Ring',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['19136']={name='Mana Igniting Cord',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['19145']={name='Robe of Volatile Power',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['19146']={name='Wristguards of Stability',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['19147']={name='Ring of Spell Power',prio='No Prio',zone='Molten Core',boss='All Bosses'},
	['16797']={name='Arcanist Mantle',prio='No Prio',zone='Molten Core',boss='Baron Geddon'},
	['16807']={name='Felheart Shoulder Pads',prio='No Prio',zone='Molten Core',boss='Baron Geddon'},
	['16836']={name='Cenarion Spaulders',prio='No Prio',zone='Molten Core',boss='Baron Geddon'},
	['16856']={name='Lawbringer Spaulders',prio='No Prio',zone='Molten Core',boss='Baron Geddon'},
	['17110']={name='Seal of the Archmagus',prio='No Prio',zone='Molten Core',boss='Baron Geddon'},
	['18563']={name='Bindings of the Windseeker',prio='No Prio',zone='Molten Core',boss='Baron Geddon'},
	['16795']={name='Arcanist Crown',prio='No Prio',zone='Molten Core',boss='Garr'},
	['16808']={name='Felheart Horns',prio='No Prio',zone='Molten Core',boss='Garr'},
	['16813']={name='Circlet of Prophecy',prio='No Prio',zone='Molten Core',boss='Garr'},
	['16821']={name='Nightslayer Cover',prio='No Prio',zone='Molten Core',boss='Garr'},
	['16834']={name='Cenarion Helm',prio='No Prio',zone='Molten Core',boss='Garr'},
	['16846']={name='Giantstalker s Helmet',prio='No Prio',zone='Molten Core',boss='Garr'},
	['16854']={name='Lawbringer Helm',prio='No Prio',zone='Molten Core',boss='Garr'},
	['16866']={name='Helm of Might',prio='No Prio',zone='Molten Core',boss='Garr'},
	['17066']={name='Drillborer Disk',prio='No Prio',zone='Molten Core',boss='Garr'},
	['17071']={name='Gutgore Ripper',prio='No Prio',zone='Molten Core',boss='Garr'},
	['17105']={name='Aurastone Hammer',prio='No Prio',zone='Molten Core',boss='Garr'},
	['18564']={name='Bindings of the Windseeker',prio='No Prio',zone='Molten Core',boss='Garr'},
	['18832']={name='Brutality Blade',prio='melee dps -> hunter',zone='Molten Core',boss='Garr'},
	['16812']={name='Gloves of Prophecy',prio='No Prio',zone='Molten Core',boss='Gehennas'},
	['16826']={name='Nightslayer Gloves',prio='No Prio',zone='Molten Core',boss='Gehennas'},
	['16849']={name='Giantstalker s Boots',prio='No Prio',zone='Molten Core',boss='Gehennas'},
	['16860']={name='Lawbringer Gauntlets',prio='No Prio',zone='Molten Core',boss='Gehennas'},
	['16862']={name='Sabatons of Might',prio='No Prio',zone='Molten Core',boss='Gehennas'},
	['16798']={name='Arcanist Robes',prio='No Prio',zone='Molten Core',boss='Golemagg the Incinerator'},
	['16809']={name='Felheart Robes',prio='No Prio',zone='Molten Core',boss='Golemagg the Incinerator'},
	['16815']={name='Robes of Prophecy',prio='No Prio',zone='Molten Core',boss='Golemagg the Incinerator'},
	['16820']={name='Nightslayer Chestpiece',prio='No Prio',zone='Molten Core',boss='Golemagg the Incinerator'},
	['16833']={name='Cenarion Vestments',prio='No Prio',zone='Molten Core',boss='Golemagg the Incinerator'},
	['16845']={name='Giantstalker s Breastplate',prio='No Prio',zone='Molten Core',boss='Golemagg the Incinerator'},
	['16853']={name='Lawbringer Chestguard',prio='No Prio',zone='Molten Core',boss='Golemagg the Incinerator'},
	['16865']={name='Breastplate of Might',prio='No Prio',zone='Molten Core',boss='Golemagg the Incinerator'},
	['17072']={name='Blastershot Launcher',prio='No Prio',zone='Molten Core',boss='Golemagg the Incinerator'},
	['17103']={name='Azuresong Mageblade',prio='No Prio',zone='Molten Core',boss='Golemagg the Incinerator'},
	['18842']={name='Staff of Dominance',prio='No Prio',zone='Molten Core',boss='Golemagg the Incinerator'},
	['16800']={name='Arcanist Boots',prio='No Prio',zone='Molten Core',boss='Lucifron'},
	['16805']={name='Felheart Gloves',prio='No Prio',zone='Molten Core',boss='Lucifron'},
	['16829']={name='Cenarion Boots',prio='No Prio',zone='Molten Core',boss='Lucifron'},
	['16859']={name='Lawbringer Boots',prio='No Prio',zone='Molten Core',boss='Lucifron'},
	['16863']={name='Gauntlets of Might',prio='No Prio',zone='Molten Core',boss='Lucifron'},
	['17109']={name='Choker of Enlightenment',prio='No Prio',zone='Molten Core',boss='Lucifron'},
	['16796']={name='Arcanist Leggings',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['16810']={name='Felheart Pants',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['16814']={name='Pants of Prophecy',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['16822']={name='Nightslayer Pants',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['16835']={name='Cenarion Leggings',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['16847']={name='Giantstalker s Leggings',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['16855']={name='Lawbringer Legplates',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['16867']={name='Legplates of Might',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['17065']={name='Medallion of Steadfast Might',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['17069']={name='Striker s Mark',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['17073']={name='Earthshaker',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['18203']={name='Eskhandar s Right Claw',prio='No Prio',zone='Molten Core',boss='Magmadar'},
	['18646']={name='The Eye of Divinity',prio='No Prio',zone='Molten Core',boss='Majordomo Executus'},
	['18703']={name='Ancient Petrified Leaf',prio='No Prio',zone='Molten Core',boss='Majordomo Executus'},
	['18803']={name='Finkle s Lava Dredger',prio='No Prio',zone='Molten Core',boss='Majordomo Executus'},
	['18805']={name='Core Hound Tooth',prio='Dagger Rogue-> Hunter/Druid',zone='Molten Core',boss='Majordomo Executus'},
	['18806']={name='Core Forged Greaves',prio='No Prio',zone='Molten Core',boss='Majordomo Executus'},
	['18808']={name='Gloves of the Hypnotic Flame',prio='No Prio',zone='Molten Core',boss='Majordomo Executus'},
	['18809']={name='Sash of Whispered Secrets',prio='No Prio',zone='Molten Core',boss='Majordomo Executus'},
	['18810']={name='Wild Growth Spaulders',prio='No Prio',zone='Molten Core',boss='Majordomo Executus'},
	['18811']={name='Fireproof Cloak',prio='No Prio',zone='Molten Core',boss='Majordomo Executus'},
	['18812']={name='Wristguards of True Flight',prio='No Prio',zone='Molten Core',boss='Majordomo Executus'},
	['19139']={name='Fireguard Shoulders',prio='No Prio',zone='Molten Core',boss='Majordomo Executus'},
	['19140']={name='Cauterizing Band',prio='No Prio',zone='Molten Core',boss='Majordomo Executus'},
	['16901']={name='Stormrage Legguards',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['16909']={name='Bloodfang Pants',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['16915']={name='Netherwind Pants',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['16922']={name='Leggings of Transcendence',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['16930']={name='Nemesis Leggings',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['16938']={name='Dragonstalker s Legguards',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['16954']={name='Judgement Legplates',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['16962']={name='Legplates of Wrath',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['17063']={name='Band of Accuria',prio='Tanks -> Melee DPS/Hunters',zone='Molten Core',boss='Ragnaros'},
	['17076']={name='Bonereaver s Edge',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['17082']={name='Shard of the Flame',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['17102']={name='Cloak of the Shrouded Mists',prio='Tank->dps',zone='Molten Core',boss='Ragnaros'},
	['17104']={name='Spinal Reaper',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['17106']={name='Malistar s Defender',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['17107']={name='Dragon s Blood Cape',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['17204']={name='Eye of Sulfuras',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['18814']={name='Choker of the Fire Lord',prio='DPS -> Healers',zone='Molten Core',boss='Ragnaros'},
	['18815']={name='Essence of the Pure Flame',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['18816']={name='Perdition s Blade',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['18817']={name='Crown of Destruction',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['19137']={name='Onslaught Girdle',prio='DPS -> Tanks',zone='Molten Core',boss='Ragnaros'},
	['19138']={name='Band of Sulfuras',prio='No Prio',zone='Molten Core',boss='Ragnaros'},
	['16799']={name='Arcanist Bindings',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16802']={name='Arcanist Belt',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16804']={name='Felheart Bracers',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16806']={name='Felheart Belt',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16817']={name='Girdle of Prophecy',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16819']={name='Vambraces of Prophecy',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16825']={name='Nightslayer Bracelets',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16827']={name='Nightslayer Belt',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16828']={name='Cenarion Belt',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16830']={name='Cenarion Bracers',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16850']={name='Giantstalker s Bracers',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16851']={name='Giantstalker s Belt',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16857']={name='Lawbringer Bracers',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16858']={name='Lawbringer Belt',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16861']={name='Bracers of Might',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['16864']={name='Belt of Might',prio='No Prio',zone='Molten Core',boss='Random Mobs'},
	['18821']={name='Quick Strike Ring',prio='No Prio',zone='Molten Core',boss='Shared Boss Drop'},
	['18822']={name='Obsidian Edged Blade',prio='No Prio',zone='Molten Core',boss='Shared Boss Drop'},
	['18823']={name='Aged Core Leather Gloves',prio='No Prio',zone='Molten Core',boss='Shared Boss Drop'},
	['18824']={name='Magma Tempered Boots',prio='No Prio',zone='Molten Core',boss='Shared Boss Drop'},
	['18829']={name='Deep Earth Spaulders',prio='No Prio',zone='Molten Core',boss='Shared Boss Drop'},
	['19142']={name='Fire Runed Grimoire',prio='No Prio',zone='Molten Core',boss='Shared Boss Drop'},
	['19143']={name='Flameguard Gauntlets',prio='No Prio',zone='Molten Core',boss='Shared Boss Drop'},
	['19144']={name='Sabatons of the Flamewalker',prio='No Prio',zone='Molten Core',boss='Shared Boss Drop'},
	['16801']={name='Arcanist Gloves',prio='No Prio',zone='Molten Core',boss='Shazzrah'},
	['16803']={name='Felheart Slippers',prio='No Prio',zone='Molten Core',boss='Shazzrah'},
	['16811']={name='Boots of Prophecy',prio='No Prio',zone='Molten Core',boss='Shazzrah'},
	['16824']={name='Nightslayer Boots',prio='No Prio',zone='Molten Core',boss='Shazzrah'},
	['16831']={name='Cenarion Gloves',prio='No Prio',zone='Molten Core',boss='Shazzrah'},
	['16852']={name='Giantstalker s Gloves',prio='No Prio',zone='Molten Core',boss='Shazzrah'},
	['16816']={name='Mantle of Prophecy',prio='No Prio',zone='Molten Core',boss='Sulfuron Harbinger'},
	['16823']={name='Nightslayer Shoulder Pads',prio='No Prio',zone='Molten Core',boss='Sulfuron Harbinger'},
	['16848']={name='Giantstalker s Epaulets',prio='No Prio',zone='Molten Core',boss='Sulfuron Harbinger'},
	['16868']={name='Pauldrons of Might',prio='No Prio',zone='Molten Core',boss='Sulfuron Harbinger'},
	['17074']={name='Shadowstrike',prio='DE',zone='Molten Core',boss='Sulfuron Harbinger'},
	['16900']={name='Stormrage Cover',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['16908']={name='Bloodfang Hood',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['16914']={name='Netherwind Crown',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['16921']={name='Halo of Transcendence',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['16929']={name='Nemesis Skullcap',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['16939']={name='Dragonstalker s Helm',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['16955']={name='Judgement Crown',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['16963']={name='Helm of Wrath',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['17064']={name='Shard of the Scale',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['17067']={name='Ancient Cornerstone Grimoire',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['17068']={name='Deathbringer',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['17075']={name='Vis kag the Bloodletter',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['17078']={name='Sapphiron Drape',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['18205']={name='Eskhandar s Collar',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['18423']={name='Head of Onyxia',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['18705']={name='Mature Black Dragon Sinew',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['18813']={name='Ring of Binding',prio='No Prio',zone='Onyxia Lair',boss='Onyxia'},
	['20890']={name='Qiraji Ornate Hilt',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ayamiss the Hunter'},
	['21466']={name='Stinger of Ayamiss',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ayamiss the Hunter'},
	['21478']={name='Bow of Taut Sinew',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ayamiss the Hunter'},
	['21480']={name='Scaled Silithid Gauntlets',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ayamiss the Hunter'},
	['21481']={name='Boots of the Desert Protector',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ayamiss the Hunter'},
	['21482']={name='Boots of the Fiery Sands',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ayamiss the Hunter'},
	['21483']={name='Ring of the Desert Winds',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ayamiss the Hunter'},
	['21484']={name='Helm of Regrowth',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ayamiss the Hunter'},
	['21485']={name='Burus Skull Fragment',prio='No Prio',zone='Ruins of AhnQiraj',boss='Buru the Gorger'},
	['21486']={name='Gloves of the Swarm',prio='No Prio',zone='Ruins of AhnQiraj',boss='Buru the Gorger'},
	['21487']={name='Slimy Scaled Gauntlets',prio='No Prio',zone='Ruins of AhnQiraj',boss='Buru the Gorger'},
	['21488']={name='Fetish of Chitinous Spikes',prio='No Prio',zone='Ruins of AhnQiraj',boss='Buru the Gorger'},
	['21489']={name='Quicksand Waders',prio='No Prio',zone='Ruins of AhnQiraj',boss='Buru the Gorger'},
	['21490']={name='Slime Kickers',prio='No Prio',zone='Ruins of AhnQiraj',boss='Buru the Gorger'},
	['21491']={name='Scaled Bracers of the Gorger',prio='No Prio',zone='Ruins of AhnQiraj',boss='Buru the Gorger'},
	['21492']={name='Manslayer of the Qiraji',prio='No Prio',zone='Ruins of AhnQiraj',boss='General Rajaxx'},
	['21493']={name='Boots of the Vanguard',prio='Feral Druids',zone='Ruins of AhnQiraj',boss='General Rajaxx'},
	['21494']={name='Southwinds Grasp',prio='No Prio',zone='Ruins of AhnQiraj',boss='General Rajaxx'},
	['21495']={name='Legplates of the Qiraji Command',prio='No Prio',zone='Ruins of AhnQiraj',boss='General Rajaxx'},
	['21496']={name='Bracers of Qiraji Command',prio='No Prio',zone='Ruins of AhnQiraj',boss='General Rajaxx'},
	['21497']={name='Boots of the Qiraji General',prio='No Prio',zone='Ruins of AhnQiraj',boss='General Rajaxx'},
	['21498']={name='Qiraji Sacrificial Dagger',prio='No Prio',zone='Ruins of AhnQiraj',boss='Kurinaxx'},
	['21499']={name='Vestments of the Shifting Sands',prio='No Prio',zone='Ruins of AhnQiraj',boss='Kurinaxx'},
	['21500']={name='Belt of the Inquisition',prio='No Prio',zone='Ruins of AhnQiraj',boss='Kurinaxx'},
	['21501']={name='Toughened Silithid Hide Gloves',prio='No Prio',zone='Ruins of AhnQiraj',boss='Kurinaxx'},
	['21502']={name='Sand Reaver Wristguards',prio='No Prio',zone='Ruins of AhnQiraj',boss='Kurinaxx'},
	['21503']={name='Belt of the Sand Reaver',prio='No Prio',zone='Ruins of AhnQiraj',boss='Kurinaxx'},
	['21455']={name='Southwind Helm',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21467']={name='Thick Silithid Chestguard',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21468']={name='Mantle of MazNadir',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21469']={name='Gauntlets of Southwind',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21470']={name='Cloak of the Savior',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21471']={name='Talon of Furious Concentration',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21472']={name='Dustwind Turban',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21473']={name='Eye of Moam',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21474']={name='Chitinous Shoulderguards',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21475']={name='Legplates of the Destroyer',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21477']={name='Ring of Fury',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21479']={name='Gauntlets of the Immovable',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['22220']={name='Plans: Black Grasp of the Destroyer',prio='No Prio',zone='Ruins of AhnQiraj',boss='Moam'},
	['21220']={name='Head of Ossirian the Unscarred',prio='Healers --> Casters --> others',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21452']={name='Staff of the Ruins',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21453']={name='Mantle of the Horusath',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21454']={name='Runic Stone Shoulders',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21456']={name='Sandstorm Cloak',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21457']={name='Bracers of Brutality',prio='DPS Warriors',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21458']={name='Gauntlets of New Life',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21459']={name='Crossbow of Imminent Doom',prio='Warrior Tanks',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21460']={name='Helm of Domination',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21461']={name='Leggings of the Black Blizzard',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21462']={name='Gloves of Dark Wisdom',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21463']={name='Ossirians Binding',prio='Hunters',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21464']={name='Shackles of the Unscarred',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['21715']={name='Sand Polished Hammer',prio='No Prio',zone='Ruins of AhnQiraj',boss='Ossirian the Unscarred'},
	['20884']={name='Qiraji Magisterial Ring',prio='No Prio',zone='Ruins of AhnQiraj',boss='Random Boss'},
	['20885']={name='Qiraji Martial Drape',prio='No Prio',zone='Ruins of AhnQiraj',boss='Random Boss'},
	['20886']={name='Qiraji Spiked Hilt',prio='No Prio',zone='Ruins of AhnQiraj',boss='Random Boss'},
	['20888']={name='Qiraji Ceremonial Ring',prio='No Prio',zone='Ruins of AhnQiraj',boss='Random Boss'},
	['20889']={name='Qiraji Regal Drape',prio='No Prio',zone='Ruins of AhnQiraj',boss='Random Boss'},
	['19863']={name='Primalists Seal (Intellect/Healing Power Ring)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19866']={name='Warblade of the Hakkari (Attack Power Off-Hand Sword)',prio='Hunters --> Melee',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19867']={name='Bloodlords Defender (Stamina/Armor One-Handed Sword)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19869']={name='Blooddrenched Grips (Stamina/Attack Power Mail Gloves)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19870']={name='Hakkari Loa Cloak (Intellect/Spirit/Healing Power Cloak)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19872']={name='Swift Razzashi Raptor (Mount)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19873']={name='Overlords Crimson Band (Stamina/Defense Ring)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19874']={name='Halberd of Smiting (Melee DPS Polearm)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19877']={name='Animists Leggings (Intellect/Spirit/Healing Power Leather Legs)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19878']={name='Bloodsoaked Pauldrons (Strength/Agility Plate Shoulders)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19893']={name='Zanzils Seal (Intellect/Spell Power Ring)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19895']={name='Bloodtinged Kilt (Intellect/Spell Power Cloth Legs)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['20038']={name='Mandokirs Sting (Agility/Stamina Bow)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['22637']={name='Primal Hakkari Idol (ZG Enchant Item)',prio='No Prio',zone='ZulGurub',boss='Bloodlord Mandokir'},
	['19944']={name='Nat Pagles Fish Terminator (Strength/Stamina Staff)',prio='No Prio',zone='ZulGurub',boss='Gahzranka'},
	['19945']={name='Forors Eyepatch (Attack Power/Critical Strike Chance Leather Helm)',prio='No Prio',zone='ZulGurub',boss='Gahzranka'},
	['19946']={name='Tigules Harpoon (Stamina/Attack Power (against Beasts) Polearm)',prio='No Prio',zone='ZulGurub',boss='Gahzranka'},
	['19947']={name='Nat Pagles Broken Reel (Spell Hit Chance Trinket)',prio='No Prio',zone='ZulGurub',boss='Gahzranka'},
	['22739']={name='Tome of Polymorph: Turtle (Teaches  Polymorph to a Mage)',prio='No Prio',zone='ZulGurub',boss='Gahzranka'},
	['19939']={name='Grileks Blood (ZG Trinket Item)',prio='No Prio',zone='ZulGurub',boss='Grilek Loot'},
	['19961']={name='Grileks Grinder (Attack Power (against Dragonkin) One-Handed Mace)',prio='No Prio',zone='ZulGurub',boss='Grilek Loot'},
	['19962']={name='Grileks Carver (Attack Power (against Dragonkin) Two-Handed Axe)',prio='No Prio',zone='ZulGurub',boss='Grilek Loot'},
	['19802']={name='Heart of Hakkar',prio='Casters/Healers -> Melee DPS',zone='ZulGurub',boss='Hakkar'},
	['19854']={name='Zinrokh Destroyer of Worlds (Stamina/Attack Power Two-Handed Sword)',prio='No Prio',zone='ZulGurub',boss='Hakkar'},
	['19852']={name='Ancient Hakkari Manslayer (Proc One-Handed Axe)',prio='No Prio',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['19853']={name='Gurubashi Dwarf Destroyer (Attack Power Gun)',prio='No Prio',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['19855']={name='Bloodsoaked Legplates (Strength/Defense Plate Legs)',prio='No Prio',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['19856']={name='The Eye of Hakkar (Attack Power/Critical Strike Chance Neck)',prio='DPS',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['19857']={name='Cloak of Consumption (Spellpower/Spell Hit Chance Cloak)',prio='No Prio',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['19859']={name='Fang of the Faceless (Attack Power/Critical Strike Chance Dagger)',prio='No Prio',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['19861']={name='Touch of Chaos (Spellpower Wand)',prio='Casters',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['19862']={name='Aegis of the Blood God (Block/Defense Shield)',prio='No Prio',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['19864']={name='Bloodcaller (Intellect/Spellpower One-Handed Sword)',prio='No Prio',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['19865']={name='Warblade of the Hakkari (Attack Power/Critical Strike Chance Main Hand Sword)',prio='No Prio',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['19876']={name='Soul Corrupters Necklace (Intellect/Spell Hit Chance Neck)',prio='Casters',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['20257']={name='Seafury Gauntlets (Strength/Intellect Mail Gloves)',prio='No Prio',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['20264']={name='Peacekeeper Gauntlets (Intellect/Healing Power Plate Gloves)',prio='No Prio',zone='ZulGurub',boss='Hakkar the Soulflayer'},
	['19942']={name='Hazzarahs Dream Thread (ZG Trinket Item)',prio='No Prio',zone='ZulGurub',boss='Hazzarah'},
	['19967']={name='Thoughtblighter (Mp5 Wand)',prio='No Prio',zone='ZulGurub',boss='Hazzarah'},
	['19968']={name='Fiery Retributer (Strength/Defense One-Handed Sword)',prio='No Prio',zone='ZulGurub',boss='Hazzarah'},
	['19896']={name='Thekals Grasp (Stamina/Critical Strike Chance Fist Weapon)',prio='No Prio',zone='ZulGurub',boss='High Priest Thekal'},
	['19897']={name='Betrayers Boots (Intellect/Spellpower Cloth Boots)',prio='No Prio',zone='ZulGurub',boss='High Priest Thekal'},
	['19898']={name='Seal of Jin (Attack Power/Critical Strike Chance Ring)',prio='No Prio',zone='ZulGurub',boss='High Priest Thekal'},
	['19899']={name='Ritualistic Legguards (Intellect/Healing Power Cloth Legs)',prio='No Prio',zone='ZulGurub',boss='High Priest Thekal'},
	['19901']={name='Zulian Slicer (Attack Power/+Skinning One-Handed Sword)',prio='No Prio',zone='ZulGurub',boss='High Priest Thekal'},
	['19902']={name='Swift Zulian Tiger (Mount)',prio='No Prio',zone='ZulGurub',boss='High Priest Thekal'},
	['20260']={name='Seafury Leggings (Strength/Intellect/Spellpower Mail Legs)',prio='No Prio',zone='ZulGurub',boss='High Priest Thekal'},
	['20266']={name='Peacekeeper Leggings (Intellect/Healing Power Plate Legs)',prio='No Prio',zone='ZulGurub',boss='High Priest Thekal'},
	['19900']={name='Zulian Stone Axe (Intellect/Attack Power Two-Handed Axe)',prio='No Prio',zone='ZulGurub',boss='High Priest Venoxis'},
	['19903']={name='Fang of Venoxis (Spellpower/Mp5 Dagger)',prio='No Prio',zone='ZulGurub',boss='High Priest Venoxis'},
	['19904']={name='Runed Bloodstained Hauberk (Attack Power/Crit Chance Mail Chest)',prio='No Prio',zone='ZulGurub',boss='High Priest Venoxis'},
	['19905']={name='Zanzils Band (Intellect/Spell Hit Chance Ring)',prio='No Prio',zone='ZulGurub',boss='High Priest Venoxis'},
	['19906']={name='Blooddrenched Footpads (Agility/Hit Chance Mail Boots)',prio='No Prio',zone='ZulGurub',boss='High Priest Venoxis'},
	['19907']={name='Zulian Tigerhide Cloak (Agility/Hit Chance Cloak)',prio='No Prio',zone='ZulGurub',boss='High Priest Venoxis'},
	['19909']={name='Will of Arlokk (Intellect/Healing Power Staff)',prio='No Prio',zone='ZulGurub',boss='High Priestess Arlokk'},
	['19910']={name='Arlokks Grasp (Shadow Damage Hit Chance Fist Weapon)',prio='No Prio',zone='ZulGurub',boss='High Priestess Arlokk'},
	['19912']={name='Overlords Onyx Band (Stamina/Block Chance Ring)',prio='No Prio',zone='ZulGurub',boss='High Priestess Arlokk'},
	['19914']={name='Panther Hide Sack (18-Slot Bag)',prio='No Prio',zone='ZulGurub',boss='High Priestess Arlokk'},
	['19919']={name='Bloodstained Greaves (Agility/Intellect Mail Boots)',prio='No Prio',zone='ZulGurub',boss='High Priestess Arlokk'},
	['19922']={name='Arlokks Hoodoo Stick (Spell Critical Strike/Healing Power Off-Hand)',prio='No Prio',zone='ZulGurub',boss='High Priestess Arlokk'},
	['19915']={name='Zulian Defender (Intellect/Spirit Shield)',prio='No Prio',zone='ZulGurub',boss='High Priestess Jeklik'},
	['19918']={name='Jekliks Crusher (Chance on Hit Two-Handed Mace)',prio='No Prio',zone='ZulGurub',boss='High Priestess Jeklik'},
	['19920']={name='Primalists Band (Intellect/Mp5 Ring)',prio='No Prio',zone='ZulGurub',boss='High Priestess Jeklik'},
	['19923']={name='Jekliks Opaline Talisman (Spellpower/Mp5 Neck)',prio='No Prio',zone='ZulGurub',boss='High Priestess Jeklik'},
	['19928']={name='Animists Spaulders (Intellect/Spirit/Healing Leather Shoulders)',prio='No Prio',zone='ZulGurub',boss='High Priestess Jeklik'},
	['20262']={name='Seafury Boots (Intellect/Spellpower Mail Boots)',prio='No Prio',zone='ZulGurub',boss='High Priestess Jeklik'},
	['20265']={name='Peacekeeper Boots (Intellect/Spellpower Plate Boots)',prio='No Prio',zone='ZulGurub',boss='High Priestess Jeklik'},
	['19871']={name='Talisman of Protection (Defense/Dodge Neck)',prio='No Prio',zone='ZulGurub',boss='High Priestess Marli'},
	['19919']={name='Bloodstained Greaves (Agility/Intellect Mail Boots)',prio='No Prio',zone='ZulGurub',boss='High Priestess Marli'},
	['19925']={name='Band of Jin (Agility/Hit Chance Ring)',prio='No Prio',zone='ZulGurub',boss='High Priestess Marli'},
	['19927']={name='Marlis Touch (Spirit/Intellect Wand)',prio='No Prio',zone='ZulGurub',boss='High Priestess Marli'},
	['19930']={name='Marlis Eye (Mp5 Trinket)',prio='No Prio',zone='ZulGurub',boss='High Priestess Marli'},
	['20032']={name='Flowing Ritual Robes (Spirit/Spellpower Cloth Chest)',prio='No Prio',zone='ZulGurub',boss='High Priestess Marli'},
	['19875']={name='Bloodstained Coif (Intellect/Attack Power Mail Helm)',prio='No Prio',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19884']={name='Jindos Judgement (Intellect/Spell Power Staff)',prio='Casters',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19885']={name='Jindos Evil Eye (Intellect/Healing Power Neck)',prio='Healers',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19886']={name='The Hexxers Cover (Intellect/Spellpower Cloth Helm)',prio='No Prio',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19887']={name='Bloodstained Legplates (Agility/Intellect Mail Pants)',prio='No Prio',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19888']={name='Overlords Embrace (Stamina/Defense Cloak)',prio='No Prio',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19889']={name='Blooddrenched Leggings (Agility/Stamina Leather Pants)',prio='No Prio',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19890']={name='Jindos Hexxer (Intellect/Healing Power One-Handed Mace)',prio='Paladins --> Druids --> Priest',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19891']={name='Jindos Bag of Whammies (Intellect/Spellpower Off-Hand)',prio='Casters',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19892']={name='Animists Boots (Intellect/Healing Power Leather Boots)',prio='No Prio',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19894']={name='Bloodsoaked Gauntlets (Strength/Defense Plate Gloves)',prio='No Prio',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19929']={name='Bloodtinged Gloves (Intellect/Spellpower Cloth Gloves)',prio='No Prio',zone='ZulGurub',boss='Jindo the Hexxer'},
	['22637']={name='Primal Hakkari Idol (ZG Enchant Item)',prio='No Prio',zone='ZulGurub',boss='Jindo the Hexxer'},
	['19940']={name='Renatakis Tooth (ZG Trinket Item)',prio='No Prio',zone='ZulGurub',boss='Renataki'},
	['19963']={name='Pitchfork of Madness (Attack Power (against Demons) Polearm)',prio='No Prio',zone='ZulGurub',boss='Renataki'},
	['19964']={name='Renatakis Soul Conduit (Spell Power/Mp5 One-Handed Sword)',prio='No Prio',zone='ZulGurub',boss='Renataki'},
	['19941']={name='Wushoolays Mane (ZG Trinket Item)',prio='No Prio',zone='ZulGurub',boss='Wushoolay'},
	['19965']={name='Wushoolays Poker (Healing Power/Mp5 Dagger)',prio='No Prio',zone='ZulGurub',boss='Wushoolay'},
	['19993']={name='Hoodoo Hunting Bow (Agility/Stamina Bow)',prio='No Prio',zone='ZulGurub',boss='Wushoolay'},
}
